// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDga-WnyQszQ6WFtKd4muhC8eMnzapt6uo',
    appId: '1:454976590652:web:64d4f5cdf0e88e2ae2c439',
    messagingSenderId: '454976590652',
    projectId: 'takehome-f0f1f',
    authDomain: 'takehome-f0f1f.firebaseapp.com',
    storageBucket: 'takehome-f0f1f.appspot.com',
    measurementId: 'G-ESZRSB7WT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwDWxbasp0aKQeVhvVvHPW8f4S_4suYbI',
    appId: '1:454976590652:android:1e2acbf21b718e8fe2c439',
    messagingSenderId: '454976590652',
    projectId: 'takehome-f0f1f',
    storageBucket: 'takehome-f0f1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgLR7FI5hqlsP3Bt8KRD4gLFPynQ9N1_c',
    appId: '1:454976590652:ios:cdd65146e3f8b5e5e2c439',
    messagingSenderId: '454976590652',
    projectId: 'takehome-f0f1f',
    storageBucket: 'takehome-f0f1f.appspot.com',
    iosClientId: '454976590652-94d86o6td6dishjbjbr28a029scivle2.apps.googleusercontent.com',
    iosBundleId: 'com.example.takeHomeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgLR7FI5hqlsP3Bt8KRD4gLFPynQ9N1_c',
    appId: '1:454976590652:ios:cdd65146e3f8b5e5e2c439',
    messagingSenderId: '454976590652',
    projectId: 'takehome-f0f1f',
    storageBucket: 'takehome-f0f1f.appspot.com',
    iosClientId: '454976590652-94d86o6td6dishjbjbr28a029scivle2.apps.googleusercontent.com',
    iosBundleId: 'com.example.takeHomeProject',
  );
}
